# Generated by Django 4.2.6 on 2023-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.CharField(max_length=32)),
                ('engine_type', models.CharField(max_length=74)),
                ('road_type', models.CharField(max_length=74)),
                ('price', models.CharField(max_length=48)),
                ('preference', models.CharField(max_length=74)),
            ],
        ),
    ]
