# Generated by Django 4.2.6 on 2023-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_carmodel_car_type_carmodel_financing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(choices=[('car_type_suv', 'suv'), ('car_type_combi', 'kombi'), ('car_type_cov', 'crossover'), ('car_type_hatchback', 'hatchback')], default='car_type_suv', max_length=32),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_type',
            field=models.CharField(choices=[('engine_type_petrol', 'benzyna'), ('engine_type_diesel', 'diesel'), ('engine_type_hybrid', 'hybryda'), ('engine_type_electric', 'elektryczny')], default='engine_type_diesel', max_length=74),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='financing',
            field=models.CharField(choices=[('financing_cash', 'gotówka/przelew'), ('financing_credit', 'kredyt'), ('financing_leasing', 'leasing'), ('financing_renting', 'najem')], default='financing_cash', max_length=48),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='person_count',
            field=models.CharField(choices=[('person_count_1', 'Tylko ja'), ('person_count_2', '2'), ('person_count_3_4', '3-4'), ('person_count_5_7', '5-7')], default='person_count_3_4', max_length=32),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='preference',
            field=models.CharField(choices=[('preference_simple', 'prostotę'), ('preference_comfort', 'komfort'), ('preference_mul_config', 'dużą możliwość konfiguracji'), ('preference_technology', 'nowinki technologiczne')], default='preference_comfort', max_length=74),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.CharField(choices=[('price_100', '0-100 tysięcy'), ('price_100_150', '100-150 tysięcy'), ('price_150_200', '150-200 tysięcy'), ('price_200', 'więcej niż 200 tysięcy')], default='price_150_200', max_length=48),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='road_type',
            field=models.CharField(choices=[('road_type_city', 'tylko miasto'), ('road_type_mixed', 'cykl mieszany'), ('road_type_route', 'głównie trasy'), ('road_type_mostly_city', 'głównie miasto, czasami trasy')], default='road_type_mixed', max_length=74),
        ),
    ]
